### ISSUE TITLE
Arduino MKR1000 Not Compiling on Mac

### ISSUE THREAD

**Issue by architkuk** [sparkfun/phant-arduino#10]
Hello,
 So Ive been trying to upload code onto my MKR1000 with the arduino software several times, yet I keep receiving the following error message which is driving me nuts.

Arduino: 1.8.3 (Mac OS X), Board: "Arduino/Genuino MKR1000"

**fork/exec /Users/xxxxxx/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/arm-none-eabi-g++: no such file or directory
Error compiling for board Arduino/Genuino MKR1000.**

Can someone help me out?

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
