### ISSUE TITLE
get() and clear() request strings are imcomplete

### ISSUE THREAD

**Issue by tcustodio** [sparkfun/phant-arduino#4]
Whenever I send a string from the get() or clear() methods the server never replied and if I send another request in succession the server would reply with a "Bad Request".
I solved this problem by adding another '\n' to the last concatenation of both methods' strings:
changed

```
result += "Connection: close\n";
```

to

```
result += "Connection: close\n\n";
```

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
