### ISSUE TITLE
HTTP/1.0 400 error (Bad request) when contacting data.sparkfun.com

### ISSUE THREAD

**Issue by jallwine** [sparkfun/phant-arduino#5]
I'm using an XBee to send data up to data.sparkfun.com using the Phant library's post method. I always get an HTTP/1.0 400 error in response. In addition to sending the request through the XBee I print it out to the Serial monitor as well (I save the result from post() to a variable and send it to the XBee and then to the Serial monitor). The request looks fine, and in fact if I copy what's printed to the serial monitor and send it through netcat on my computer it works fine. This led me to assume something was going wrong in transit through the XBee, so I wanted to see exactly what the Phant server was getting. I started my own Phant server to see what exactly the server was getting, and the request goes through no problem. Any thoughts on what could be my problem?

**Comment by vinceis1337** [comment]
@jallwine -
Please use my version:
https://github.com/vinceis1337/phant-arduino

I have an open pull request to fix this issue:
https://github.com/sparkfun/phant-arduino/pull/3

My version is just a hack but it appears that their server doesn't process incoming requests properly.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
