### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by cah-oster** [sparkfun/phant-arduino#6]
Trying the example from https://learn.sparkfun.com/tutorials/esp8266-thing-hookup-guide/all#example-sketch-posting-to-phant
I'm using an official sparkfun esp8266 thing

I get 400 Bad Request with:
0 analog missing from sent data.

If I print the url to serial and copy paste it into my web browser, it works.  I tried the edited code from issue 3 and it still doesn't work.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
