### ISSUE TITLE
Error compiling on MKR1000

### ISSUE THREAD

**Issue by sven250** [sparkfun/phant-arduino#7]
When i try to compile my sketch for my Genuino MKR1000 (hackster edition), i get the following error:

```
C:\Users\***\Documents\arduino-1.6.8\libraries\phant-arduino-master\src\Phant.cpp:27:22: fatal error: pgmspace.h: No such file or directory

 #include "pgmspace.h"

                      ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino MKR1000.
```

When I try to compile on the Arduino Uno settings, it works fine. But I don't have an Uno...

After copying the pgmspace.h file to the C:***\arduino-1.6.8\libraries\phant-arduino-master\src folder the error changed to:

```
Arduino: 1.6.8 (Windows 7), Board:"Arduino/Genuino MKR1000"

C:\Users\***\Documents\arduino-1.6.8\libraries\phant-arduino-master\src\Phant.cpp: In member function 'void Phant::add(String, double)':

C:\Users\***\Documents\arduino-1.6.8\libraries\phant-arduino-master\src\Phant.cpp:152:26: error: 'dtostrf' was not declared in this scope

   dtostrf(data, 1, 4, tmp);

                          ^

C:\Users\***\Documents\arduino-1.6.8\libraries\phant-arduino-master\src\Phant.cpp: In member function 'void Phant::add(const __FlashStringHelper*, double)':

C:\Users\***\Documents\arduino-1.6.8\libraries\phant-arduino-master\src\Phant.cpp:162:26: error: 'dtostrf' was not declared in this scope

   dtostrf(data, 1, 4, tmp);

                          ^

C:\Users\***\Documents\arduino-1.6.8\libraries\phant-arduino-master\src\Phant.cpp: In member function 'void Phant::add(String, float)':

C:\Users\***\Documents\arduino-1.6.8\libraries\phant-arduino-master\src\Phant.cpp:174:26: error: 'dtostrf' was not declared in this scope

   dtostrf(data, 1, 4, tmp);

                          ^

C:\Users\***\Documents\arduino-1.6.8\libraries\phant-arduino-master\src\Phant.cpp: In member function 'void Phant::add(const __FlashStringHelper*, float)':

C:\Users\***\Documents\arduino-1.6.8\libraries\phant-arduino-master\src\Phant.cpp:184:26: error: 'dtostrf' was not declared in this scope

   dtostrf(data, 1, 4, tmp);

                          ^

exit status 1
Error compiling for board Arduino/Genuino MKR1000.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```

I hope anyone can help me!

**Comment by puckettgw** [comment]
I think you may need to include <stdlib.h> to get that dtostrf function.

**Comment by sven250** [comment]
> I think you may need to include <stdlib.h> to get that dtostrf function.

That didn't work...
The problem with dtostrf() is that it's a AVR function, which means it can't be used on ARM boards (the MKR1000 is a 32-bit ARM based board).
I read something about the stringf() function, but I don't know the difference between them. Maybe anyone can replace dtostrf() with stringf()?
Thanks in advance!

**Comment by tshrjn** [comment]
Same problem with Intel Galileo2.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
