### ISSUE TITLE
The data does not load to the cloud

### ISSUE THREAD

**Issue by Natflue** [sparkfun/phant-arduino#9]
I made program with data does not come into the cloud when I copy test URL from the serial monitor, and paste the URL to explore, write the ok data to the cloud when I use the post, it does not ??
 
  phant.add ( "bin_in", "post");
  phant.add ( "bin_out", false);
  phant.add ( "temp_1", 98.6);
  phant.add ( "temp_2", 98.6);
  phant.add ( "temp_3", 98.6);

  Serial.println ( "---- ---- HTTP POST");
  Serial.println (phant.post ());
  client.println (phant.post ());

I use the library

#include <SPI.h>
#include <Ethernet.h>
#include <Phant.h>

I have used
Arduino UNO
Arduino Ethernet

---- TEST URL -----
http://data.sparkfun.com/input/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt?private_key=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz&bin_in=url&bin_out=22&temp_1=0.1234&temp_2=98.6000&temp_3=98.6000

---- HTTP POST ----
POST /input/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt HTTP / 1.1
Host: data.sparkfun.com
Phant-Private-Key: zzzzzzzzzzzzzzzzzzzzzzzz
Connection: close
Content-Type: application / x-www-form-urlencoded
Content-Length: 66

bin_in = item & bin_out = 0 & temp_1 = 98.6000 and 98.6000 temp_2 = & temp_3 = 98.6000

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
